// Generated by GPT-5

#include "Hub75.hpp"

#include "FreeRTOS.h"
#include "task.h"
#include <cstdlib>
#include <cstdint>

// Screen dimensions
constexpr int WIDTH  = 64;
constexpr int HEIGHT = 64;

// Fire intensity buffer
static uint8_t fire[HEIGHT][WIDTH];

// Simple fire color palette (0–255 → RGB in 0xBBGGRR format)
static uint32_t palette[256];

// Initialize palette: black → red → orange → yellow → white
static void init_palette() {
    for (int i = 0; i < 256; i++) {
        int r, g, b;
        if (i < 85) {          // black → red
            r = i * 3;
            g = 0;
            b = 0;
        } else if (i < 170) {  // red → orange → yellow
            r = 255;
            g = (i - 85) * 3;
            b = 0;
        } else {               // yellow → white
            r = 255;
            g = 255;
            b = (i - 170) * 3;
        }
        // Convert RGB → 0xBBGGRR
        palette[i] = (uint32_t(b) << 16) | (uint32_t(g) << 8) | r;
    }
}

// Initialize fire buffer
static void init_fire() {
    for (int y = 0; y < HEIGHT; y++) {
        for (int x = 0; x < WIDTH; x++) {
            fire[y][x] = 0;
        }
    }
}

// Update fire simulation
static void update_fire() {
    // Bottom row acts as "fuel"
    for (int x = 0; x < WIDTH; x++) {
        fire[HEIGHT - 1][x] = (rand() % 256) > 150 ? 255 : 0;
    }

    // Propagate upward
    for (int y = 1; y < HEIGHT; y++) {
        for (int x = 0; x < WIDTH; x++) {
            int below = fire[y][(x + rand() % 3 - 1 + WIDTH) % WIDTH];  // neighbor
            int val = below - (rand() % 40);
            if (val < 0) val = 0;
            fire[y - 1][x] = val;
        }
    }
}

// Render fire to display
static void render_fire() {
  Hub75& matrix = Hub75::instance();
    for (int y = 0; y < HEIGHT; y++) {
        for (int x = 0; x < WIDTH; x++) {
          matrix.set_pixel(x, y, palette[fire[y][x]]);
        }
    }
}

void fire_task(TaskHandle_t task) {
    init_palette();
    init_fire();

    while (true) {
        update_fire();
        render_fire();
        vTaskDelay(pdMS_TO_TICKS(30));  // ~33 FPS
    }
}
