// Generated by GPT-5

#include "apps/effects/effects.hpp"
#include "Hub75.hpp"
#include "ControlServer.hpp"

#include <cstdlib>
#include <ctime>
#include <vector>
#include <cstdint>

constexpr unsigned WIDTH = 64;
constexpr unsigned HEIGHT = 64;
constexpr unsigned NUM_DROPS = 20;
constexpr unsigned FRAME_DELAY_MS = 50;
constexpr unsigned TAIL_LENGTH = 7;

// Colors in BGR888
static uint32_t COLOR_HEAD = 0xFF0000; // bright blue (B=0xFF)
static uint32_t COLOR_TAIL = 0x800000; // dim blue (used as base, gets scaled)

struct Drop {
  int x;
  int y;
  int speed;
};

static uint32_t fade_color(uint32_t base, float factor) {
  // Extract BGR components
  uint8_t b = (base >> 16) & 0xFF;
  uint8_t g = (base >> 8) & 0xFF;
  uint8_t r = base & 0xFF;

  b = static_cast<uint8_t>(b * factor);
  g = static_cast<uint8_t>(g * factor);
  r = static_cast<uint8_t>(r * factor);

  return (b << 16) | (g << 8) | r;
}

void rain_task(TaskHandle_t task) {
  Hub75& matrix = Hub75::instance();
  std::srand(static_cast<unsigned>(std::time(nullptr)));

  std::vector<Drop> drops(NUM_DROPS);

  // Initialize drops at random positions
  for (auto &d : drops) {
    d.x = std::rand() % WIDTH;
    d.y = std::rand() % HEIGHT;
    d.speed = 1 + (std::rand() % 3); // speed 1–3 px/frame
  }

  while (true) {
    // Clear screen
    for (unsigned y = 0; y < HEIGHT; y++) {
      for (unsigned x = 0; x < WIDTH; x++) {
        matrix.set_pixel888(x, y, 0x000000);
      }
    }

	Netconn* conn;
	if ((conn = ControlServer::instance().receive_conn(pcTaskGetName(nullptr), false)) != nullptr) {
	  COLOR_HEAD = std::stoi(conn->getline(" "));
	  COLOR_TAIL = std::stoi(conn->getline());
	  ControlServer::instance().give_conn(pcTaskGetTaskName(nullptr), conn);
	}

    // Update and draw drops
    for (auto &d : drops) {
      d.y += d.speed;
      if (d.y >= HEIGHT + TAIL_LENGTH) {
        d.x = std::rand() % WIDTH;
        d.y = -(std::rand() % 10);
        d.speed = 1 + (std::rand() % 3);
      }

      // Draw head
      if (d.y >= 0 && d.y < static_cast<int>(HEIGHT)) {
        matrix.set_pixel888(d.x, d.y, COLOR_HEAD);
      }

      // Draw tail (fading upwards)
      for (unsigned t = 1; t <= TAIL_LENGTH; t++) {
        int ty = d.y - t;
        if (ty >= 0 && ty < static_cast<int>(HEIGHT)) {
          float fade = 1.0f - (static_cast<float>(t) / (TAIL_LENGTH + 1));
          uint32_t tail_color = fade_color(COLOR_TAIL, fade);
          matrix.set_pixel888(d.x, ty, tail_color);
        }
      }
    }

    vTaskDelay(pdMS_TO_TICKS(FRAME_DELAY_MS));
  }
}
